export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    REFRESH_TOKEN_REQUEST: "REFRESH_TOKEN_REQUEST",
    REFRESH_TOKEN_SUCCESS: "REFRESH_TOKEN_SUCCESS",
    REFRESH_TOKEN_FAILURE: "REFRESH_TOKEN_FAILURE"
}

export const userConstants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE"
}

export const viewerConstants = {
    VIEWER_REGISTER_REQUEST: "VIEWER_REGISTER_REQUEST",
    VIEWER_REGISTER_SUCCESS: "VIEWER_REGISTER_SUCCESS",
    VIEWER_REGISTER_FAILURE: "VIEWER_REGISTER_FAILURE"
}

export const customerConstants = {
    GET_CUSTOMER_REQUEST: "GET_CUSTOMER_REQUEST",
    GET_CUSTOMER_SUCCESS: "GET_CUSTOMER_SUCCESS",
    GET_CUSTOMER_FAILURE: "GET_CUSTOMER_FAILURE",
    CUSTOMER_UPDATE_REQUEST: "CUSTOMER_UPDATE_REQUEST",
    CUSTOMER_UPDATE_SUCCESS: "CUSTOMER_UPDATE_SUCCESS",
    CUSTOMER_UPDATE_FAILURE: "CUSTOMER_UPDATE_FAILURE"
}

export const categoryConstants = {
    SEARCH_CATEGORY_REQUEST: "SEARCH_CATEGORY_REQUEST",
    SEARCH_CATEGORY_SUCCESS: "SEARCH_CATEGORY_SUCCESS",
    SEARCH_CATEGORY_FAILURE: "SEARCH_CATEGORY_FAILURE",
    SEARCH_ALL_CATEGORIES: "SEARCH_ALL_CATEGORIES",
    SEARCH_CATEGORY_FILTER: "SEARCH_CATEGORY_FILTER",
    CATEGORY_FILTERS_BY_SLUGS: "CATEGORY_FILTERS_BY_SLUGS",
    CATEGORIES_INIT: "CATEGORIES_INIT",
}

export const productConstants = {
    PRODUCTS_NEW_DATA: "PRODUCTS_NEW_DATA",
    GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",
    GET_ADD_PRODUCTS_REQUEST: "GET_ADD_PRODUCTS_REQUEST",
    GET_ADD_PRODUCTS_SUCCESS: "GET_ADD_PRODUCTS_SUCCESS",
    GET_ADD_PRODUCTS_FAILURE: "GET_ADD_PRODUCTS_FAILURE",
    GET_ALL_PRODUCTS_BY_SLUG_REQUEST: "GET_ALL_PRODUCTS_BY_SLUG_REQUEST",
    GET_ALL_PRODUCTS_BY_SLUG_SUCCESS: "GET_ALL_PRODUCTS_BY_SLUG_SUCCESS",
    GET_ALL_PRODUCTS_BY_SLUG_FAILURE: "GET_ALL_PRODUCTS_BY_SLUG_FAILURE",
    PRODUCT_SEARCH_BY_TEXT: "PRODUCT_SEARCH_BY_TEXT",
    PRODUCT_SEARCH_BY_CATEGORY_IN: "PRODUCT_SEARCH_BY_CATEGORY_IN",
    SEARCH_PRODUCTS_REQUEST: "SEARCH_PRODUCTS_REQUEST",
    SEARCH_PRODUCTS_SUCCESS: "SEARCH_PRODUCTS_SUCCESS",
    SEARCH_PRODUCTS_FAILURE: "SEARCH_PRODUCTS_FAILURE",
    PRODUCT_SEARCH_BY_CATEGORY_SLUG: "PRODUCT_SEARCH_BY_CATEGORY_SLUG",
    PRODUCTS_INIT: "PRODUCTS_INIT",
}

export const searchConstants = {
    SEARCH_REQUEST: "SEARCH_REQUEST",
    SEARCH_SUCCESS: "SEARCH_SUCCESS",
    SEARCH_FAILURE: "SEARCH_FAILURE",
    SEARCH_BOX_CLEAR: "SEARCH_BOX_CLEAR",
}

export const cartConstants = {
    CART_REQUEST: "CART_REQUEST",
    CART_SUCCESS: "CART_SUCCESS",
    CART_FAILURE: "CART_FAILURE",
    ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
    UPDATE_CART_REQUEST: "UPDATE_CART_REQUEST",
    UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
    UPDATE_CART_FAILURE: "UPDATE_CART_FAILURE",
    CLEAR_CART_REQUEST: "CLEAR_CART_REQUEST",
    CLEAR_CART_SUCCESS: "CLEAR_CART_SUCCESS",
    CLEAR_CART_FAILURE: "CLEAR_CART_FAILURE"
}